#הכנסת 2 מספרים וביצוע פעולות חשבון
num1 = int(input("please enter a number "))
num2 = int(input("please enter a second number "))
print("the sum of the numbers are :", num1+num2 )
print("the diffrence of the numbers are :", num1-num2 )
print("the product of the numbers are :", num1*num2 )
print("the division of the numbers are :", num1/num2 )
print("the integer division of the numbers are :", num1//num2 )
print("the exponention of the numbers are :", num1**num2 )
print("the reminder of the numbers are :", num1%num2 )
print(f"the sum of the numbers are : {num1+num2} ")
print(f"the diffrence of the numbers are : {num1-num2}" )
print(f"the product of the numbers are :{num1*num2} ")
print(f"the division of the numbers are :{num1/num2}" )
print(f"the integer division of the numbers are :{ num1//num2}" )
print(f"the exponention of the numbers are :{ num1**num2}" )
print(f"the reminder of the numbers are :{ num1%num2}" )